version: '3'
services:
  mongo-standalone:
    image: 'mongo:latest'
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/var/lib/mongo
  springboot-docker-container:
    image: 3-candles-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: "mongo-standalone"
      SPRING_DATA_MONGODB_PORT: "27016"
    build: .
    depends_on:
      - mongo-standalone
volumes:
  mongo-data: