spring:
    data.mongodb:
        host: localhost
        port: 27017
        database: stocksDB

    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: ALWAYS

nse:
    data:
        bhavcopy: "src/main/resources/data/"