spring:
    data.mongodb:
        host: localhost
        port: 27017
        database: stocksDB

    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: ALWAYS

nse:
    data:
        bhavcopy: "data/"
        holiday: "NSEHolidays.txt"
        nifty50: "Nifty50List.txt"

strategy:
    countOfCandlesConsidered: 3

#server.port: 8081