spring:
    data.mongodb:
        host: localhost
        port: 27017
        database: stocksDB

    batch:
        job:
            enabled: false
        jdbc:
            initialize-schema: ALWAYS

nse:
    data:
        bhavcopy: "src/main/resources/data/"
        holiday: "src/main/resources/NSEHolidays.txt"
        nifty50: "src/main/resources/Nifty50List.txt"

strategy:
    countOfCandlesConsidered: 3